#!/usr/bin/env bash
# Installs Nginx web server with configure it:
# Listens on port 80.
# Returns a page containing "Hello World" when queried
# at the root with a curl GET request.

sudo pt-get -y update 
sudo apt-get -y install nginx

# Start nginx
sudo service nginx start

# Configure nginx to listen on port 80 and serve "Hello World!" on the root page
echo "server {
	listen 80;
	location / {echo  'Hello World!';
			}
		}" > /etc/nginx/sites-available/default

# Reload nginx configuration
sudo service nginx restart

