#!/usr/bin/env bash

# configuring nginx to have a custom 404 page

 sudo apt-get -y update
 sudo apt-get -y install nginx

 # is used to allow incoming connections to the Nginx HTTP server through the firewall through port 80. using the ufw (Uncomplicated Firewall) command-line tool.
 sudo ufw allow 'Nginx HTTP'

 # change the owner of the /var/www directory to the current user recursively. To allow modification of the files in the directory.
 sudo chown -R $USER /var/www

 # set up a page containing "Hello World" when queried at the root with a curl GET request.
 echo 'Hello World!' > /var/www/html/index.nginx-debian.html

 # change the owner of the /etc/nginx/sites-available/defaul/etc/nginx/sites-available/default,to enable modification of the config file.
 sudo chown -R $USER /etc/nginx/sites-available/default

 # Making a backup of the default file, in case something goes wrong
 sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

 # Setting up /redirect_me to a permanent redirect to my LinkedIn account
 sudo sed -i '24i\rewrite ^/redirect_me https://www.linkedin.com/in/mayen-kalu-inim/;' /etc/nginx/sites-available/default
 sudo service nginx restart

 # Set up a 404 page
 echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
 sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
 
 sudo service nginx restart
