#!/usr/bin/env bash
# configures HAproxy - load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get install -y haproxy

# Configure HAProxy
echo '
frontend www-http
        bind *:80
        mode http
        default_backend www-backend
backend www-backend
        balance roundrobin
        server 150499-web-01 107.23.61.222:80 check
        server 150499-web-02 54.242.163.162:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart
