#!/usr/bin/env bash
# configures HAproxy - load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo echo '
frontend www-http
        bind *:80
        mode http
        default_backend www-backend
backend www-backend
        balance roundrobin
        server 150499-web-01 54.175.135.48:80 check
        server 150499-web-02 52.86.170.107:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart
